### ISSUE TITLE
People Counting

### ISSUE THREAD

**Issue by kent-williams** [kriswiner/STHS34PF80#2]
Thanks for sharing your code for this new sensor!

How are you planning on deciphering the direction the person is moving to people count? I have done this in the past with a single grid-based PIR or thermal sensor, but it's not obvious how that can be done with a single one of these sensors? Are you planning on mounting [this](https://user-images.githubusercontent.com/6698410/259259769-05fe8b1b-525f-4b68-bb6b-8ce0bd80aaf1.jpg) perpendicular to the doorway and leveraging two of them to know which one activates before or after the other?

**Comment by kriswiner** [comment]
"Are you planning on mounting this
<https://github.com/kriswiner/STHS34PF80/issues/1#issuecomment-1670457409>
perpendicular
to the doorway and leveraging two of them to know which one activates
before or after the other?"

Yes, I have done this with the Calipile, that is used two of them and
compared interrupt times to determine ingress or egress. This works very
well, and I expect it to work well for the STHS34PF80 (I will know this
week). The challenge here is not functionality but BOM cost and power
usage. Detecting direction of travel cannot be done with only a single PIR
sensor uless one were to use something like the Grideye (AMG8833
<https://www.tindie.com/products/onehorse/grid-eye-8-x-8-ir-array/>)
sensor, which is actually 64 separate sensors, so expensive and a power
hog...

**Comment by kent-williams** [comment]
That's encouraging to hear! I built something very similar to this several years ago but used the [AK9750 sensor](https://datasheetspdf.com/pdf-file/1028134/AKM/AK9750/1), which has a quad PIR array and was able to decipher direction quite well. The only issue was that it was quite susceptible to outside light shining in a room. 

![image](https://github.com/kriswiner/STHS34PF80/assets/479648/7fc50130-6ed9-4219-b4a3-9cda32e4a964)

**Comment by kriswiner** [comment]
I tested the AK9750 but its range wasn't that large. Its presence detection
algorithm was hard for me to understand or use properly. Typical AK.

Two AK9754 single-pixel IR sensors worked quite well but again, the range
was limited to ~10 cm or so and besides, this sensor is obsolete now. Too
bad because it was super cheap and very low power.

The Calipile worked well, and we had a few startups testing it. In the end,
the temperature drift was a killer for the low-power (i.e., battery
lifetime) requirement.

The internal temperature compensation of the STHS34PF80 should avoid the
need for frequent threshold recalibration and the internal presence
detection ASIC seems capable of people detection without manual threshold
setting. So overall, it looks like ST might have gotten it right for this
application.

Now that I have a prototype design it should be a simple matter of testing.

What is your interest in this kind of device?

I am looking for marketing partners...

**Comment by kent-williams** [comment]
It's definitely a shame all the AK detection sensors are obsolete, they did work great for some applications.

Looking forward to playing with the STHS34PF80, I've been waiting for something like it for a long time.

My interests are just exploratory for now. Will you be putting your board up for sale?

**Comment by kriswiner** [comment]
Maybe the breakout...depends on interest.

**Comment by kent-williams** [comment]
Appreciate the responses!
